SELECT count(title) NB_FILM, 
C.NAME, 
A.FIRST_NAME,
A.LAST_NAME
FROM FILM F
INNER JOIN FILM_ACTOR FA ON F.FILM_ID = FA.FILM_ID
INNER JOIN ACTOR A ON FA.ACTOR_ID = A.ACTOR_ID
INNER JOIN FILM_CATEGORY FC ON F.FILM_ID = FC.FILM_ID
INNER JOIN CATEGORY C ON FC.CATEGORY_ID = C.CATEGORY_ID
WHERE A.FIRST_NAME = "JOHNNY" 
AND A.LAST_NAME = "LOLLOBRIGIDA"
GROUP BY C.NAME
;

SELECT count(title) NB_FILM, 
C.NAME, 
A.FIRST_NAME,
A.LAST_NAME
FROM FILM F
INNER JOIN FILM_ACTOR FA ON F.FILM_ID = FA.FILM_ID
INNER JOIN ACTOR A ON FA.ACTOR_ID = A.ACTOR_ID
INNER JOIN FILM_CATEGORY FC ON F.FILM_ID = FC.FILM_ID
INNER JOIN CATEGORY C ON FC.CATEGORY_ID = C.CATEGORY_ID
WHERE A.FIRST_NAME = "JOHNNY" 
AND A.LAST_NAME = "LOLLOBRIGIDA"
GROUP BY C.NAME
HAVING NB_FILM > 3
;

SELECT AVG(DATEDIFF(return_date, rental_date)) DUREE_MOY
,A.FIRST_NAME
,A.LAST_NAME
FROM RENTAL R
INNER JOIN INVENTORY I ON R.INVENTORY_ID = I.INVENTORY_ID
INNER JOIN FILM F ON I.FILM_ID = F.FILM_ID
INNER JOIN FILM_ACTOR FA ON F.FILM_ID = FA.FILM_ID
INNER JOIN ACTOR A ON FA.ACTOR_ID = A.ACTOR_ID
GROUP BY A.FIRST_NAME
,A.LAST_NAME
;

SELECT SUM(AMOUNT) TOTAL
,C.FIRST_NAME
,C.LAST_NAME
FROM PAYMENT P
INNER JOIN CUSTOMER C ON P.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.FIRST_NAME
,C.LAST_NAME
ORDER BY TOTAL DESC
;